spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatopdb
    username: chatop
    password: pwdchatop
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true
  file:
    upload-dir: uploads
  springdoc:
    packagesToScan: com.example.chatoprentalbackend.controller